help:
	@echo "Some notes as to run this stuff"
	@echo "deploy-dev    - deploy the dev environment"


deploy-dev:
	@zappa deploy dev

run-local:
	@env/bin/python app.py

unit-test:
	@env/bin/nosetests
